import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import jsxA11y from "eslint-plugin-jsx-a11y";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      ...jsxA11y.flatConfigs.recommended.rules,
    },
  },
  {
    files: ["src/components/ui/label.tsx"],
    rules: {
      // Generated primitive: association happens at each call site via htmlFor.
      "jsx-a11y/label-has-associated-control": "off",
    },
  },
  {
    files: ["src/hooks/use-mobile.ts"],
    rules: {
      // Generated by shadcn sidebar; the delayed matchMedia read avoids a
      // server/client hydration mismatch on the first paint.
      "react-hooks/set-state-in-effect": "off",
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/server/db/migrations/**",
  ]),
]);

export default eslintConfig;
